In [1]:
import numpy as np

In [2]:
ave_random=np.random.random((7,5))

np.set_printoptions(precision=4)
ave_random

array([[0.104 , 0.2706, 0.5613, 0.1856, 0.7673],
       [0.7468, 0.3537, 0.2615, 0.0088, 0.6995],
       [0.6717, 0.8394, 0.0281, 0.2976, 0.677 ],
       [0.0492, 0.7715, 0.8596, 0.0528, 0.7942],
       [0.0892, 0.1732, 0.4177, 0.5314, 0.6952],
       [0.2563, 0.1359, 0.0105, 0.9174, 0.6993],
       [0.4279, 0.2412, 0.4464, 0.3687, 0.7816]])

In [3]:
my_array=[1,2,3,4]
my_array

[1, 2, 3, 4]

In [4]:
#Структурированный массив


In [5]:
employee_data_def=[('name','S6'),('height','f8')]
employee_array=np.zeros((2),dtype=employee_data_def)
employee_array

array([(b'', 0.), (b'', 0.)], dtype=[('name', 'S6'), ('height', '<f8')])

In [6]:
employee_array[0]=('aleeex',80)

In [7]:
employee_array

array([(b'aleeex', 80.), (b'',  0.)],
      dtype=[('name', 'S6'), ('height', '<f8')])

In [8]:
ave_array=(np.arange(24)).reshape(2,3,4)
trial_ave=np.append(ave_array,[5,6,7,8])
trial_ave.reshape((7,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 5,  6,  7,  8]])

In [9]:
ave_array.shape

(2, 3, 4)

In [10]:
arrays=np.arange(32).reshape(4,2,4)
arrays

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [11]:
stack1=np.stack(arrays,axis=2)
stack1

array([[[ 0,  8, 16, 24],
        [ 1,  9, 17, 25],
        [ 2, 10, 18, 26],
        [ 3, 11, 19, 27]],

       [[ 4, 12, 20, 28],
        [ 5, 13, 21, 29],
        [ 6, 14, 22, 30],
        [ 7, 15, 23, 31]]])

In [12]:
my_list=[1,2,3,4]
my_array=np.array(my_list)
my_array

array([1, 2, 3, 4])

In [14]:
my_tuple=(1,3,4,5)
my_array1=np.array(my_tuple)
my_array1


array([1, 3, 4, 5])

In [17]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
np.linspace(0,30,11,retstep=True)

(array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.]),
 np.float64(3.0))

In [21]:
## Задача сверху разместить 11 стульев в комнате 30 м

In [22]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
array_ave=np.arange(35).reshape(7,5)
array_ave


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [33]:
zero_mod2=0==(array_ave%2)
zero_mod4=0==(array_ave%4)

In [31]:
sub_array=array_ave[zero_mod2]
sub_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34])

In [34]:
combined_mask=np.logical_and(zero_mod2,zero_mod4)

In [36]:
sub_array2=array_ave[combined_mask]
sub_array2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32])

In [38]:
ave_3d_array=np.arange(70).reshape(2,7,5)
ave_3d_array


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [39]:
5*ave_3d_array-10

array([[[-10,  -5,   0,   5,  10],
        [ 15,  20,  25,  30,  35],
        [ 40,  45,  50,  55,  60],
        [ 65,  70,  75,  80,  85],
        [ 90,  95, 100, 105, 110],
        [115, 120, 125, 130, 135],
        [140, 145, 150, 155, 160]],

       [[165, 170, 175, 180, 185],
        [190, 195, 200, 205, 210],
        [215, 220, 225, 230, 235],
        [240, 245, 250, 255, 260],
        [265, 270, 275, 280, 285],
        [290, 295, 300, 305, 310],
        [315, 320, 325, 330, 335]]])

In [43]:
lef_mat=np.arange(6).reshape(2,3)
right_mat=np.arange(15).reshape(3,5)
np.dot(lef_mat,right_mat)


array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [44]:
#Умножение матриц

In [46]:
ave_vektor=np.arange(5)*7
ave_3d_array/ave_vektor


C:\Users\zhcri\AppData\Local\Temp\ipykernel_13020\202130511.py:2: RuntimeWarning: divide by zero encountered in divide
  ave_3d_array/ave_vektor
C:\Users\zhcri\AppData\Local\Temp\ipykernel_13020\202130511.py:2: RuntimeWarning: invalid value encountered in divide
  ave_3d_array/ave_vektor


array([[[       nan, 0.14285714, 0.14285714, 0.14285714, 0.14285714],
        [       inf, 0.85714286, 0.5       , 0.38095238, 0.32142857],
        [       inf, 1.57142857, 0.85714286, 0.61904762, 0.5       ],
        [       inf, 2.28571429, 1.21428571, 0.85714286, 0.67857143],
        [       inf, 3.        , 1.57142857, 1.0952381 , 0.85714286],
        [       inf, 3.71428571, 1.92857143, 1.33333333, 1.03571429],
        [       inf, 4.42857143, 2.28571429, 1.57142857, 1.21428571]],

       [[       inf, 5.14285714, 2.64285714, 1.80952381, 1.39285714],
        [       inf, 5.85714286, 3.        , 2.04761905, 1.57142857],
        [       inf, 6.57142857, 3.35714286, 2.28571429, 1.75      ],
        [       inf, 7.28571429, 3.71428571, 2.52380952, 1.92857143],
        [       inf, 8.        , 4.07142857, 2.76190476, 2.10714286],
        [       inf, 8.71428571, 4.42857143, 3.        , 2.28571429],
        [       inf, 9.42857143, 4.78571429, 3.23809524, 2.46428571]]])

In [47]:
new=np.array(np.arange(24)).reshape(2,3,4)*10+5
new

array([[[  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [63]:
np.append(ave_array,new,axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [56]:
ave_array.shape

(2, 3, 4)

In [62]:
np.append(ave_array,new,axis=2).shape

(2, 3, 8)

In [58]:
new.shape

(2, 3, 4)

In [64]:
insert_array=np.insert(new,1,666,axis=0)

In [65]:
insert_array


array([[[  5,  15,  25,  35],
        [ 45,  55,  65,  75],
        [ 85,  95, 105, 115]],

       [[666, 666, 666, 666],
        [666, 666, 666, 666],
        [666, 666, 666, 666]],

       [[125, 135, 145, 155],
        [165, 175, 185, 195],
        [205, 215, 225, 235]]])

In [67]:
del_array=np.empty(new.shape)
np.copyto(del_array,new)
np.delete(del_array,1,axis=0)

array([[[  5.,  15.,  25.,  35.],
        [ 45.,  55.,  65.,  75.],
        [ 85.,  95., 105., 115.]]])

In [69]:
aplha=np.array([[1,2],[3,4]])
beta=np.array([[5,6]])
tg=np.concatenate((aplha,beta),axis=0)
tg

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
tg1=np.append(aplha,beta,axis=0)
tg1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
arrays=np.zeros((5,3,4))
for n in range(5):
    arrays[n]=np.random.randn(3,4)
arrays

array([[[-0.20781338, -1.73806643,  1.31707098, -0.84858713],
        [ 0.70042557, -1.58994776,  0.30916166, -0.35069998],
        [-0.16920388,  0.71454117,  0.27375722, -0.39632592]],

       [[ 1.32581272, -0.1443999 ,  0.43288087,  0.62572629],
        [ 0.01283008, -0.35147554, -0.09745182,  0.15245577],
        [-0.60307268,  0.83843801, -0.18312952,  0.85076452]],

       [[ 1.02132784,  0.75914705, -0.06592845, -0.9518737 ],
        [-0.2528983 , -0.67505562, -1.18837358,  0.42615478],
        [-0.34507156, -1.10627971,  1.47487176, -2.58317285]],

       [[-0.84873009, -1.414262  , -0.07525734,  0.4705952 ],
        [-0.50601662, -1.68556345,  0.36964167, -0.49711118],
        [-0.2051272 ,  0.30026882,  0.38936092,  0.80111082]],

       [[ 0.17194164, -0.47047228,  0.65513825,  0.37681675],
        [-1.08825259,  0.10761839,  1.87559843,  2.47246018],
        [-0.27396598, -0.40811496,  0.45835017, -0.67754335]]])

In [87]:
s0=np.split(new,3,axis=1)
s0


[array([[[  5,  15,  25,  35]],
 
        [[125, 135, 145, 155]]]),
 array([[[ 45,  55,  65,  75]],
 
        [[165, 175, 185, 195]]]),
 array([[[ 85,  95, 105, 115]],
 
        [[205, 215, 225, 235]]])]

In [91]:
over=np.array(np.arange(24)).reshape(3,8)
over

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [92]:
over.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [93]:
for n in over.flat:
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [94]:
np.fliplr(over)

array([[ 7,  6,  5,  4,  3,  2,  1,  0],
       [15, 14, 13, 12, 11, 10,  9,  8],
       [23, 22, 21, 20, 19, 18, 17, 16]])

In [95]:
np.flipud(over)

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  4,  5,  6,  7]])

In [98]:
np.roll(over,4)

array([[20, 21, 22, 23,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [100]:
np.rot90(over)

array([[ 7, 15, 23],
       [ 6, 14, 22],
       [ 5, 13, 21],
       [ 4, 12, 20],
       [ 3, 11, 19],
       [ 2, 10, 18],
       [ 1,  9, 17],
       [ 0,  8, 16]])

In [101]:
np.tile(over,5)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4,  5,  6,  7,
         0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4,  5,  6,  7,
         0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15,
         8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15,
         8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 16, 17, 18, 19, 20, 21, 22, 23,
        16, 17, 18, 19, 20, 21, 22, 23, 16, 17, 18, 19, 20, 21, 22, 23,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [103]:
np.tile(over,(3,2))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 16, 17, 18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 16, 17, 18, 19, 20, 21, 22, 23],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 16, 17, 18, 19, 20, 21, 22, 23]])

In [104]:
np.repeat(over,3)

array([ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,
        5,  6,  6,  6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11,
       11, 11, 12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15, 16, 16, 16,
       17, 17, 17, 18, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 21, 22, 22,
       22, 23, 23, 23])